/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loginpage;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.util.*;
/**
 *
 * @author pushk
 */
public class Activity extends javax.swing.JFrame {

    /**
     * Creates new form Activity
     */
    public Activity(String visit) throws SQLException {
    this.setUndecorated(true);
    this.setAlwaysOnTop(false);
    this.setResizable(false);
    this.setVisible(true);
    visitor=visit;
    initComponents();
    message.requestFocusInWindow();
    organise();
    this.setLocationRelativeTo(null);
    status.setVisible(false);
    }

     String visitor,today,visitString,m;
     int date1,month;
     
    public void organise() throws SQLException
    {
        
         SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");  
         Date date = new Date();
         today = formatter.format(date);
         
         
         
             try {
                 Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                 String url="jdbc:sqlserver://localhost:1433;databaseName=master;user=sa;password=1234";
                 Connection con=DriverManager.getConnection(url);
                 String s="select date_visit from visit_log where visitor_id=? order by(date_visit) DESC";
                 PreparedStatement p=con.prepareStatement(s);
                 p.setString(1,visitor);
                 ResultSet rs=p.executeQuery();
                 if(rs.next()!=false)
                 {
                 m=rs.getString("date_visit");
                 if(!(m.substring(5,7).equals(today.substring(5,7))))
                 {
                 String sql=("update visitor set flag_message=0");
                 PreparedStatement pst=con.prepareStatement(sql);
                 int update=pst.executeUpdate();
                 String sql1=("update visitor set flag_visit=0");
                 PreparedStatement pst1=con.prepareStatement(sql1);
                 update=pst1.executeUpdate();
                 }
                 }
             } catch (ClassNotFoundException ex) {
                 Logger.getLogger(Activity.class.getName()).log(Level.SEVERE, null, ex);
             }
             
         
         
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDatePickerUtil1 = new org.jdatepicker.util.JDatePickerUtil();
        jDatePickerUtil2 = new org.jdatepicker.util.JDatePickerUtil();
        jDatePickerUtil3 = new org.jdatepicker.util.JDatePickerUtil();
        sqlDateModel1 = new org.jdatepicker.impl.SqlDateModel();
        utilCalendarModel1 = new org.jdatepicker.impl.UtilCalendarModel();
        utilDateModel1 = new org.jdatepicker.impl.UtilDateModel();
        jDatePickerUtil4 = new org.jdatepicker.util.JDatePickerUtil();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        purpose = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        status = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        visit_date = new org.jdesktop.swingx.JXDatePicker();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        message = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        visit = new org.jdesktop.swingx.JXDatePicker();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("     x");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 0, 43, 43));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SET APPOINTMENT");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 479, 36));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 556, 110));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setText("SET VISIT DATE :");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 116, 35));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("     x");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 0, 43, 43));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel5.setText("PURPOSE :");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 116, 31));

        purpose.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PERSONAL", "LEGAL", "ADMINISTRAVTVE", "OTHER" }));
        jPanel3.add(purpose, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 249, 40));

        jLabel6.setText("STATUS:");
        jLabel6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 116, 32));

        status.setColumns(20);
        status.setRows(5);
        jScrollPane2.setViewportView(status);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 397, 99));

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton2.setText("REQUEST VISIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 490, 160, 34));
        jPanel3.add(visit_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 240, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, 550, 550));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setText("Type Message ( max characters: 100 ) :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 234, 41));

        message.setColumns(20);
        message.setRows(5);
        jScrollPane1.setViewportView(message);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 426, 209));

        jButton1.setText("SEND");
        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, 99, 35));

        jPanel6.setBackground(new java.awt.Color(102, 102, 102));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(visit, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 150, 250, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("SEND MESSAGE");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 250, 30));

        jPanel6.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 110));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 110));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 510, 550));

        jLabel10.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("# Only a message or an appointment can be made for the current month");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 710, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginpage/new.jpg"))); // NOI18N
        jLabel8.setText("ljepf");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 790));

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SEND MESSAGE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 510, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
                if(message.getText().length()>100)
                {
                    JOptionPane.showMessageDialog(null,"A message must be of less than 100 characters");
                }
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                 String url="jdbc:sqlserver://localhost:1433;databaseName=master;user=sa;password=1234";
                 Connection con=DriverManager.getConnection(url);
                 String sql=("select flag_message from visitor where visitor_id=?");
                 PreparedStatement pst=con.prepareStatement(sql);
                 pst.setString(1,visitor);
                 ResultSet rs=pst.executeQuery();
                 rs.next();
                 int flag=rs.getInt("flag_message");
                 if(flag==1)
                 {
                     
                     JOptionPane.showMessageDialog(null,"You have used up your messaging privileges for this month");
                 } 
                 else
                 {
                     String sql2="UPDATE visitor set vmessage=? where visitor_id=?";
                     PreparedStatement pst2=con.prepareStatement(sql2);
                     pst2.setString(1,message.getText());
                     pst2.setString(2,visitor);
                     int update2=pst2.executeUpdate();
                     if(update2>0)
                     {
                         JOptionPane.showMessageDialog(null,"Your message has been sent successfully");
                     }
                     else
                     {
                         JOptionPane.showMessageDialog(null,"There was an error in sending your mesage, please try again ");
                     }
                     
                     
                 }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Activity.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Activity.class.getName()).log(Level.SEVERE, null, ex);
        }
                
    }//GEN-LAST:event_jButton1ActionPerformed

    
  
    
    
    
    //tday=Integer.parseInt(today.substring(9,10));
            
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");  
        visitString=formatter.format(visit_date.getDate());
        if(!(today.substring(5,7).equals(visitString.substring(5,7)))) {
           status.setVisible(true);
        status.setText("Appointments can only be made for the current month");
        }
        else
        {
            java.sql.Date cdate;
            
             try {
                 Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                 String url="jdbc:sqlserver://localhost:1433;databaseName=master;user=sa;password=1234";
                 Connection con=DriverManager.getConnection(url);
                 String sql=("select flag_visit from visitor where visitor_id=?");
                 PreparedStatement pst=con.prepareStatement(sql);
                 pst.setString(1,visitor);
                 ResultSet rs=pst.executeQuery();
                 rs.next();
                 int flag=rs.getInt("flag_visit");
                 if(flag==1)
                 {
                     status.setVisible(true);
                     status.setText("You have used up your appointment for this month");
                 }
                 else
                 {
                     
                     String sql2=("select visit_no from visit_log where visitor_id=?");
                     PreparedStatement pst2=con.prepareStatement(sql2);
                     pst2.setString(1,visitor);
                     ResultSet rs2=pst2.executeQuery();
                     if(rs2.next()==false)
                     {
                     String sql3="insert into visit_log values(?,?,?,?,?)";
                     PreparedStatement pst3=con.prepareStatement(sql3);
                     pst3.setInt(1,1);
                     pst3.setString(2,visitor);
                     pst3.setString(3,"Granted");
                    // cdate=java.sql.Date.valueOf(visit.getDate());
                     pst3.setString(4,visitString);
                     pst3.setString(5,purpose.getSelectedItem().toString());
                     int update=pst3.executeUpdate();
                     
                     if(update>0)
                     {
                         status.setVisible(true);
                         status.setText("Your requested appointment has been granted \n Date of appointment: "+ visitString);
                     }
                     else
                     {
                         status.setVisible(true);
                         status.setText("Request Denied");
                     }
             
                     }
                     else
                     {
                     int visit_no=rs2.getInt("visit_no");
                     String sql3="insert into visit_log values(?,?,?,?,?)";
                     PreparedStatement pst3=con.prepareStatement(sql3);
                     pst3.setInt(1,++visit_no);
                     pst3.setString(2,visitor);
                     pst3.setString(3,"Granted");
                     //cdate=java.sql.Date.valueOf(visit.getDate());
                     pst3.setString(4,visitString);
                     pst3.setString(5,purpose.getSelectedItem().toString());
                     int update=pst3.executeUpdate();
                         if(update>0)
                     {
                         status.setVisible(true);
                         status.setText("Your requested appointment has been granted \n Date of appointment: "+ visitString);
                     }
                     else
                     {
                         status.setVisible(true);
                         status.setText("Request Denied");
                     }
                     }
                    
           
                 }
             } catch (ClassNotFoundException ex) {
                 Logger.getLogger(Activity.class.getName()).log(Level.SEVERE, null, ex);
             } catch (SQLException ex) {
                Logger.getLogger(Activity.class.getName()).log(Level.SEVERE, null, ex);
               
            }
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        MainVisit mv=new MainVisit(visitor);
        mv.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Activity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Activity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Activity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Activity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Activity(" ").setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Activity.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private org.jdatepicker.util.JDatePickerUtil jDatePickerUtil1;
    private org.jdatepicker.util.JDatePickerUtil jDatePickerUtil2;
    private org.jdatepicker.util.JDatePickerUtil jDatePickerUtil3;
    private org.jdatepicker.util.JDatePickerUtil jDatePickerUtil4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea message;
    private javax.swing.JComboBox<String> purpose;
    private org.jdatepicker.impl.SqlDateModel sqlDateModel1;
    private javax.swing.JTextArea status;
    private org.jdatepicker.impl.UtilCalendarModel utilCalendarModel1;
    private org.jdatepicker.impl.UtilDateModel utilDateModel1;
    private org.jdesktop.swingx.JXDatePicker visit;
    private org.jdesktop.swingx.JXDatePicker visit_date;
    // End of variables declaration//GEN-END:variables
}
