/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loginpage;

import java.sql.Connection;
import java.util.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author pushk
 */
public class Changes extends javax.swing.JFrame {

    /**
     * Creates new form Changes
     */
    public Changes(String pri) throws ParseException {
    this.setUndecorated(true);
    this.setAlwaysOnTop(false);
    this.setResizable(false);
    this.setVisible(true);
    initComponents();   
    prisoner=pri;
    this.setLocationRelativeTo(null);
    fname.requestFocusInWindow();
    prisoner_id.setText(pri);
      try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=master;user=sa;password=1234";
            Connection con=DriverManager.getConnection(url);
            String sql="select * from prisoner where prisoner_id=?";
            PreparedStatement pst=con.prepareStatement(sql);
            pst.setString(1,prisoner);
            ResultSet rs=pst.executeQuery();
            rs.next();
            fname.setText(rs.getString("fname"));
            lname.setText(rs.getString("lname"));
            age.setText(rs.getString("age"));
            crime.setText(rs.getString("crime"));
            officer.setText(rs.getString("officer_assigned"));
            sentence.setText(rs.getString("sentence"));
            gender.setText(rs.getString("gender"));
            date_release=rs.getString("date_release");
            SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            Date date1 =  df.parse(date_release);
            date.setDate(date1);
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Med_Report.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    String prisoner,date_release;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lname = new javax.swing.JTextField();
        crime = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        sentence = new javax.swing.JTextField();
        officer = new javax.swing.JTextField();
        gender = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        fname = new javax.swing.JTextField();
        work = new javax.swing.JComboBox<>();
        date = new org.jdesktop.swingx.JXDatePicker();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        prisoner_id = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("FIRST NAME :");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 130, 34));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("LAST NAME :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 120, 20));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CRIME :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 80, 34));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("JOB ASSIGNED :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 158, 34));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("AGE :");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 60, 34));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("SENTENCE :");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, -1, 34));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("OFFICER ASSIGNED :");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, -1, -1));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("RELEASE DATE :");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, -1, 34));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("GENDER :");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, -1, 34));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 260, 10));

        lname.setBackground(new java.awt.Color(51, 51, 51));
        lname.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        lname.setForeground(new java.awt.Color(255, 255, 255));
        lname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lname.setBorder(null);
        lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameActionPerformed(evt);
            }
        });
        jPanel2.add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 240, 30));

        crime.setBackground(new java.awt.Color(51, 51, 51));
        crime.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        crime.setForeground(new java.awt.Color(255, 255, 255));
        crime.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        crime.setBorder(null);
        crime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crimeActionPerformed(evt);
            }
        });
        jPanel2.add(crime, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 260, 30));

        age.setBackground(new java.awt.Color(51, 51, 51));
        age.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        age.setForeground(new java.awt.Color(255, 255, 255));
        age.setBorder(null);
        age.setCaretColor(new java.awt.Color(255, 255, 255));
        age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageActionPerformed(evt);
            }
        });
        jPanel2.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 90, 30));

        sentence.setBackground(new java.awt.Color(51, 51, 51));
        sentence.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        sentence.setForeground(new java.awt.Color(255, 255, 255));
        sentence.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sentence.setBorder(null);
        sentence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sentenceActionPerformed(evt);
            }
        });
        jPanel2.add(sentence, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 130, 260, 40));

        officer.setBackground(new java.awt.Color(51, 51, 51));
        officer.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        officer.setForeground(new java.awt.Color(255, 255, 255));
        officer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        officer.setBorder(null);
        jPanel2.add(officer, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 190, 270, 40));

        gender.setBackground(new java.awt.Color(51, 51, 51));
        gender.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        gender.setForeground(new java.awt.Color(255, 255, 255));
        gender.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        gender.setBorder(null);
        jPanel2.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 320, 270, 30));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 230, 300, 10));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 350, 300, 10));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 170, 300, 10));
        jPanel2.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 110, 10));
        jPanel2.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 260, 10));
        jPanel2.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 260, 10));

        fname.setBackground(new java.awt.Color(51, 51, 51));
        fname.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        fname.setForeground(new java.awt.Color(255, 255, 255));
        fname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fname.setBorder(null);
        jPanel2.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 250, 30));

        work.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CHOOSE A JOB", "COOK", "CLEANER", "ENTERTAINMENT", "SWEEPER", "STONE MASON", "LABOURER" }));
        work.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workActionPerformed(evt);
            }
        });
        jPanel2.add(work, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 250, -1));
        jPanel2.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 260, 290, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 1080, 520));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MAKE CHANGES FOR PRISONER ID: ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 46, 350, 50));

        prisoner_id.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        prisoner_id.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(prisoner_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 55, 280, 30));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("     x");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, 43, 43));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("     -");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 10, 43, 43));

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setText("APPLY CHANGES");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 650, 270, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameActionPerformed

    private void crimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crimeActionPerformed

    private void ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageActionPerformed

    private void sentenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sentenceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sentenceActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=master;user=sa;password=1234";
            Connection con=DriverManager.getConnection(url);
            String sql_fname="update prisoner set fname=? where  prisoner_id=?";
            PreparedStatement pst_fname=con.prepareStatement(sql_fname);
            pst_fname.setString(1,fname.getText());
            pst_fname.setString(2,prisoner);
            int f=pst_fname.executeUpdate();
            String sql_lname="update prisoner set lname=? where  prisoner_id=?";
            PreparedStatement pst_lname=con.prepareStatement(sql_lname);
            pst_lname.setString(1,lname.getText());
            pst_lname.setString(2,prisoner);
            int l=pst_lname.executeUpdate();
            String sql_age="update prisoner set age=? where  prisoner_id=?";
            PreparedStatement pst_age=con.prepareStatement(sql_age);
            pst_age.setString(1,age.getText());
            pst_age.setString(2,prisoner);
            int a=pst_age.executeUpdate();
            String sql_work="update prisoner set work=? where  prisoner_id=?";
            PreparedStatement pst_work=con.prepareStatement(sql_work);
            if(work.getSelectedIndex()==0)
            {
                pst_work.setString(1,"No job assigned");
            }
            else
            {
                pst_work.setString(1,work.getSelectedItem().toString());
            }
            
            pst_work.setString(2,prisoner);
            int w=pst_work.executeUpdate();
            
            String sql_crime="update prisoner set crime=? where  prisoner_id=?";
            PreparedStatement pst_crime=con.prepareStatement(sql_crime);
            pst_crime.setString(1,crime.getText());
            pst_crime.setString(2,prisoner);
            int c=pst_crime.executeUpdate();
            java.sql.Date cdate;
            
                String sql_date="update prisoner set date_release=? where  prisoner_id=?";
                PreparedStatement pst_date=con.prepareStatement(sql_date);
                String date1;
                SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");  
                date1=formatter.format(date.getDate());
                pst_date.setString(1,date1);
                pst_date.setString(2,prisoner);
                int d=pst_date.executeUpdate();
            
            String sql_sentence="update prisoner set sentence=? where  prisoner_id=?";
            PreparedStatement pst_sentence=con.prepareStatement(sql_sentence);
            pst_sentence.setString(1,sentence.getText());
            pst_sentence.setString(2,prisoner);
            int s=pst_sentence.executeUpdate();
            
            String sql_officer="update prisoner set officer_assigned=? where  prisoner_id=?";
            PreparedStatement pst_officer=con.prepareStatement(sql_officer);
            pst_officer.setString(1,officer.getText());
            pst_officer.setString(2,prisoner);
            int o=pst_officer.executeUpdate();
            
            JOptionPane.showMessageDialog(null,"CHANGES HAVE BEEN APPLIED SUCCESSFULLY");
            
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Med_Report.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void workActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_workActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Changes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Changes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Changes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Changes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Changes(" ").setVisible(true);
                } catch (ParseException ex) {
                    Logger.getLogger(Changes.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField age;
    private javax.swing.JTextField crime;
    private org.jdesktop.swingx.JXDatePicker date;
    private javax.swing.JTextField fname;
    private javax.swing.JTextField gender;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField officer;
    private javax.swing.JLabel prisoner_id;
    private javax.swing.JTextField sentence;
    private javax.swing.JComboBox<String> work;
    // End of variables declaration//GEN-END:variables
}
