/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loginpage;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author pushk
 */
public class Med_Report extends JFrame implements ActionListener {

    /**
     * Creates new form Med_Report
     */
    int flag;
    public Med_Report(int a,String s) {
    this.setUndecorated(true);
    this.setAlwaysOnTop(false);
    this.setResizable(false);
    this.setVisible(true);
    initComponents();
    this.setLocationRelativeTo(null);
    button.addActionListener(this);
    flag=a;
    caller=s;
    
    if(flag==1)
    {
       try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=master;user=sa;password=1234";
            Connection con=DriverManager.getConnection(url);
            String sql="select p.fname,p.lname,p.prisoner_id as prisoner from prisoner p,visitor v where v.prisoner_id=p.prisoner_id and visitor_id=?";
            PreparedStatement pst=con.prepareStatement(sql);
            pst.setString(1,caller);
            ResultSet rs=pst.executeQuery();
            rs.next();
            prisoner_display.setText("Prisoner: ");
            prisoner_id.setText(rs.getString("fname")+" "+rs.getString("lname"));
            prisoner=rs.getString("prisoner");
    }catch(ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Med_Report.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }
    }


    String caller,prisoner;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        prisoner_display = new javax.swing.JLabel();
        prisoner_id = new javax.swing.JTextField();
        bloodgroup = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        reportno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        bloodph = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        platelete = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        injury1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        disease = new javax.swing.JTextField();
        button = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 378, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(75, 80, 81));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        prisoner_display.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        prisoner_display.setForeground(new java.awt.Color(255, 255, 255));
        prisoner_display.setText("Prisoner ID:");
        jPanel2.add(prisoner_display, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        prisoner_id.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        prisoner_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prisoner_idActionPerformed(evt);
            }
        });
        jPanel2.add(prisoner_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 160, 30));

        bloodgroup.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jPanel2.add(bloodgroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 160, 30));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Blood Group:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Report No:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        reportno.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        reportno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportnoActionPerformed(evt);
            }
        });
        jPanel2.add(reportno, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 179, 160, 30));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Blood PH:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 42, -1, 15));

        bloodph.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jPanel2.add(bloodph, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 170, 30));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Platelete:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 93, -1, -1));

        platelete.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        platelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plateleteActionPerformed(evt);
            }
        });
        jPanel2.add(platelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, 170, 30));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Injury:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 152, -1, -1));

        injury1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jPanel2.add(injury1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 150, 170, 30));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Disease:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 212, -1, -1));

        disease.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jPanel2.add(disease, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 209, 170, 30));

        button.setBackground(new java.awt.Color(204, 204, 0));
        button.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        button.setForeground(new java.awt.Color(0, 0, 0));
        button.setText("SEARCH");
        button.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonMouseClicked(evt);
            }
        });
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });
        jPanel2.add(button, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 260, 130, 40));

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 112, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 910, 390));

        jPanel3.setBackground(new java.awt.Color(75, 80, 81));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("MEDICAL REPORT");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 254, 41));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("     x");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 0, 43, 43));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("     -");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, 43, 43));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 140));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed
try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=master;user=sa;password=1234";
            Connection con=DriverManager.getConnection(url);
    if(flag==2)
    {
        
       
            String sql="select * from med_report where prisoner_id=?";
            PreparedStatement pst=con.prepareStatement(sql);
            pst.setString(1,prisoner_id.getText());
            ResultSet rs=pst.executeQuery();
            if(rs.next()==false)
            {
                JOptionPane.showMessageDialog(null,"The medical report for this prisoner does not exist");
            }
            else
            {
            injury1.setText(rs.getString("injury"));
            bloodgroup.setText(rs.getString("blood_group"));
            bloodph.setText(rs.getString("blood_ph"));
            reportno.setText(rs.getString("report_no"));
            platelete.setText(rs.getString("platelete"));
            disease.setText(rs.getString("infection"));
            }
    }
           else
    {
         String sql="select * from med_report where prisoner_id=?";
            PreparedStatement pst=con.prepareStatement(sql);
            pst.setString(1,prisoner);
            ResultSet rs=pst.executeQuery();
            if(rs.next()==false)
            {
                JOptionPane.showMessageDialog(null,"The medical report for this prisoner does not exist");
            }
            else
            {
            injury1.setText(rs.getString("injury"));
            bloodgroup.setText(rs.getString("blood_group"));
            bloodph.setText(rs.getString("blood_ph"));
            reportno.setText(rs.getString("report_no"));
            platelete.setText(rs.getString("platelete"));
            disease.setText(rs.getString("infection"));
                    }
    }
    
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Med_Report.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_buttonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(flag==1)
        {
            MainVisit mv=new MainVisit(caller);
            mv.setVisible(true);
            dispose();
        }
        if(flag==2)
        {
            MainAut ma=new MainAut(caller);
            ma.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMouseClicked
       
    }//GEN-LAST:event_buttonMouseClicked

    private void prisoner_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prisoner_idActionPerformed
         
    }//GEN-LAST:event_prisoner_idActionPerformed

    private void reportnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reportnoActionPerformed

    private void plateleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plateleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plateleteActionPerformed

    
   
   
     
   
    
 

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        /* Create and display the form */
      
               new Med_Report(0," ").setVisible(true);
    };
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bloodgroup;
    private javax.swing.JTextField bloodph;
    private javax.swing.JButton button;
    private javax.swing.JTextField disease;
    private javax.swing.JTextField injury1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField platelete;
    private javax.swing.JLabel prisoner_display;
    private javax.swing.JTextField prisoner_id;
    private javax.swing.JTextField reportno;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
     //   throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}



